import uuid
from datetime import datetime
from typing import TYPE_CHECKING, Literal

from sqlalchemy import BigInteger, CheckConstraint, DateTime
from sqlmodel import AutoString, Field, Relationship, SQLModel

from app.core.config import MAX_UPLOAD_BYTES
from app.models.common import utc_now

if TYPE_CHECKING:
    from app.models.analysis import Analysis

VideoStatus = Literal["awaiting_upload", "uploaded", "rejected"]


class VideoBase(SQLModel):
    """Fields the table shares with the API's VideoPublic (app/schemas.py)."""

    original_filename: str
    duration_s: float | None = None  # known once the worker has probed the file
    codec: str | None = None


class Video(VideoBase, table=True):
    __tablename__ = "videos"
    __table_args__ = (
        CheckConstraint(f"declared_size BETWEEN 1 AND {MAX_UPLOAD_BYTES}", name="declared_size"),
        CheckConstraint("status IN ('awaiting_upload', 'uploaded', 'rejected')", name="status"),
    )

    id: uuid.UUID = Field(primary_key=True)  # generated by the browser
    object_name: str = Field(unique=True)  # videos/<id>.mp4
    declared_size: int = Field(sa_type=BigInteger)
    status: VideoStatus = Field(default="awaiting_upload", sa_type=AutoString)
    size_bytes: int | None = Field(default=None, sa_type=BigInteger)  # from the GCS event
    gcs_generation: int | None = Field(default=None, sa_type=BigInteger)
    width: int | None = None
    height: int | None = None
    error: str | None = None
    created_at: datetime = Field(default_factory=utc_now, sa_type=DateTime(timezone=True))
    uploaded_at: datetime | None = Field(default=None, sa_type=DateTime(timezone=True))

    analyses: list["Analysis"] = Relationship(back_populates="video")
