"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-28 17:17:48.503638

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "videos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("original_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("declared_size", sa.BigInteger(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("gcs_generation", sa.BigInteger(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("codec", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('awaiting_upload', 'uploaded', 'rejected')", name=op.f("ck_videos_status")
        ),
        sa.CheckConstraint(
            "declared_size BETWEEN 1 AND 209715200", name=op.f("ck_videos_declared_size")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
        sa.UniqueConstraint("object_name", name=op.f("uq_videos_object_name")),
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("pipeline_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sample_fps", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("frames_sampled", sa.Integer(), nullable=True),
        sa.Column("detection_count", sa.Integer(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'done', 'failed')", name=op.f("ck_analyses_status")
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_analyses_video_id_videos")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
        sa.UniqueConstraint("video_id", "pipeline_version", name="one_result_set"),
    )
    op.create_table(
        "detections",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("sample_idx", sa.Integer(), nullable=False),
        sa.Column("det_rank", sa.SmallInteger(), nullable=False),
        sa.Column("video_id", sa.Uuid(), nullable=False),
        sa.Column("t_seconds", sa.Float(), nullable=False),
        sa.Column("class_id", sa.SmallInteger(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("x1", sa.Float(), nullable=False),
        sa.Column("y1", sa.Float(), nullable=False),
        sa.Column("x2", sa.Float(), nullable=False),
        sa.Column("y2", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "0 <= x1 AND x1 < x2 AND x2 <= 1 AND 0 <= y1 AND y1 < y2 AND y2 <= 1",
            name=op.f("ck_detections_box"),
        ),
        sa.CheckConstraint(
            "confidence > 0 AND confidence <= 1", name=op.f("ck_detections_confidence")
        ),
        sa.CheckConstraint("sample_idx >= 0", name=op.f("ck_detections_sample_idx")),
        sa.CheckConstraint("t_seconds >= 0", name=op.f("ck_detections_t_seconds")),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
            name=op.f("fk_detections_analysis_id_analyses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"], ["videos.id"], name=op.f("fk_detections_video_id_videos")
        ),
        sa.PrimaryKeyConstraint(
            "analysis_id", "sample_idx", "det_rank", name=op.f("pk_detections")
        ),
    )
    op.create_index("ix_detections_video_t", "detections", ["video_id", "t_seconds"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_detections_video_t", table_name="detections")
    op.drop_table("detections")
    op.drop_table("analyses")
    op.drop_table("videos")
    # ### end Alembic commands ###
